name: OLibs
version: 1.7`.2
main: com.github.SuperOrca.olibs.OLibs
api-version: '1.20'
authors: [SuperOrca, others]
description: Collection of libs used by my plugins
website: https://superorca.github.io/