name: OLibs
version: 1.6.1
main: io.github.superorca.olibs.OLibs
api-version: '1.20'
authors: [SuperOrca, others]
description: Collection of libs used by my plugins
website: https://superorca.github.io/